backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "글"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "태그", name: "tag", widget: "string", default: "Blog", required: false }
      - { label: "요약", name: "excerpt", widget: "text", required: false, hint: "글 목록에 보여줄 짧은 요약" }
      - { label: "본문", name: "body", widget: "markdown" }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "layouts/post.njk" }
